sudo: false
os:
  - linux
  - osx
arch:
  - amd64
  - ppc64le
language: node_js
node_js:
  - node
  - '10'
  - '9'
  - '8'
  - '7'
  - '6'
  - '5'
  - '4'
  - '0.12'
  - '0.10'
jobs:
    exclude:
       - node-js: 0.10
         arch: ppc64le
       - node-js: 0.12
         arch: ppc64le
